### ISSUE TITLE
Image listener not working?

### ISSUE THREAD

**Issue by mikeleftwich** [josephdadams/presentationbridge-client#12]
I'm using presentationbridge-client v1.0.8 with ProPresenter 6.5.3 on a MacBook Pro running macOS 11.6 (Big Sur). Everything is currently local to my machine. The text listener, lower third listener, and stage display listener all work great, but the image listener just shows a blank (black) screen. I have tried Chrome, Safari, Opera, and Edge browsers (all Mac versions), all with the same result. I've read over the docs a couple of times and I don't see anything wrong. I can turn the logo on and off at the bridge while using the image listener and that works. I just don't get the screen image. What am I missing?

Thanks, and thank you so very much for this tool!

Mike

**Comment by jrviz** [comment]
I'm not sure presentationbridge-client sends image data. Only current/next slide text/notes

If Joseph is around he can say what might be possible. Presentation Bridge has support for images but I don't think the PP API publishes them.

**Comment by josephdadams** [comment]
I did not implement the image listener functions in presentationbridge-client, only in the original presentationbridge which you would have to use in the browser. It's very prone to be inaccurate as it has to poll ProPresenter for this information and if you change any slides, the cache can be off. So it's a neat feature but not very practical which is why I did not develop it for the client to send along to the bridge. Sorry this wasn't documented better.

**Comment by jrviz** [comment]
Our replies just crossed. I have got images working  by using the image ID from the cs payload and doing an http image GET in PBC. I send this to the presentationbridge - subject to a switch setting to enable this.

**Comment by josephdadams** [comment]
great!

**Comment by mikeleftwich** [comment]
Thanks very much for the prompt replies! And @jrviz thanks for coming up with a solution! I look forward to seeing it in action.

What I'm trying to accomplish is to show lyrics, images, or whatever PP is displaying in a lower third or corner PiP in our livestream (we use Livestream Studio 6). I'm considering using an embedded browser in an overlay and use a text listener in that embedded browser. I would use a separate overlay with an image listener to show images, but for song lyrics, sermon notes, etc. I'd probably not try to display the backgrounds and just stick with text. How reliable would that be? Can you suggest a better way? I have a number of choices besides this, like an RSS feed, a stream (RTMP, RTSP, Zixi, etc.), NDI input, CSV over HTTP, and a few other possibilities.

**Comment by josephdadams** [comment]
Fixed in latest
