### ISSUE TITLE
Stage Display Notes

### ISSUE THREAD

**Issue by tgladson** [josephdadams/presentationbridge-client#15]
In version 1.0.10 (and 9), the Presentation Bridge Client is not reading Stage Display Notes in ProPresenter 6. I had to downgrade to 1.0.8 to get it to work. I am on MacOS. 

It is connected to ProPresenter as it shows connected and I can see Current and Next Slide in the Monitor, but it is not picking up the Stage Display notes where I am simply entering: Companion:3,3

**Comment by jrviz** [comment]
Is the command terminated with a ;

**Comment by tgladson** [comment]
It is not. And it isn't in 1.0.8 where it is working. Is that a change in 1.0.9 and 1.0.10?

**Comment by MichaelAllen** [comment]
Looks like there was [a change](https://github.com/josephdadams/presentationbridge-client/commit/5338aac9cf5c5ea7cfa42fa7eac6a1e664807fbd#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R660) in 1.0.9 where the semicolon is now required.

Here is the bit in the help file where it mentions needing the semicolon: https://github.com/josephdadams/presentationbridge-client/blob/10f1fbe4909803d087aa1507d01f84268366f829/help.md?plain=1#L18

**Comment by tgladson** [comment]
Thanks for that. If that is the case, I believe the examples need updated. I will verify a semi-colon works next time I am at church.

**Comment by MichaelAllen** [comment]
@tgladson : Good call on the examples. I will send over a PR to get those fixed.

@jrviz : Since this is potentially a breaking change for some people (the `;` was optional before, so many people probably skipped it), is it possible to add a note to the release tag for v1.0.9 giving a heads up that it is required now?

**Comment by josephdadams** [comment]
Can’t we also just read the string before parsing the commands and append a semicolon programmatically if it’s not there?

**Comment by jrviz** [comment]
OK. I'll take a look at some ideas. I made the change to allow multiple commands to occur anywhere in the notes string which may also contain other notes.

**Comment by josephdadams** [comment]
Fixed in #17
