### ISSUE TITLE
Vista cue with decimal point does not work. 

### ISSUE THREAD

**Issue by tgladson** [josephdadams/presentationbridge-client#24]
I ran into an issue this past Sunday that was new. We had a Vista cue with a decimal point, for example 1.5 and it would not work. In ProPresenter stage notes, I entered "Vista: 2, 1.5;" (for example) and Presentation Bridge Client did not pick it up. I renamed the queue to a whole number and updated stage notes and it worked. So, is there an issue with cues with decimal points? Not a huge deal. I can get around it, but wanted to report it.

**Comment by jrviz** [comment]
Version 1.0.14 published which should allow decimal point in parameters
