### ISSUE TITLE
wrong app icon for macos

### ISSUE THREAD

**Issue by josephdadams** [josephdadams/presentationbridge-client#3]
On MacOS, the app icon is a unicorn; I think this is the problem: https://github.com/josephdadams/presentationbridge-client/blob/master/static/Icon.png

It should get replaced with something else

**Comment by jrviz** [comment]
I get the same icon for the app on Windows. Perhaps time for an update 😊

From: Joseph Adams ***@***.***>
Sent: 29 July 2021 19:25
To: josephdadams/presentationbridge-client ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [josephdadams/presentationbridge-client] wrong app icon for macos (#3)


On MacOS, the app icon is a unicorn; I think this is the problem: https://github.com/josephdadams/presentationbridge-client/blob/master/static/Icon.png<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjosephdadams%2Fpresentationbridge-client%2Fblob%2Fmaster%2Fstatic%2FIcon.png&data=04%7C01%7C%7C9b4bd47d4a6e45ac70d308d952be22da%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637631798844075485%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=QN5g00XB600qhDOFoazkg2XqtJCRKgG4Ck2USpyv19Q%3D&reserved=0>

It should get replaced with something else

**Comment by josephdadams** [comment]
I have a PSD somewhere for a logo, I'll try to dig it up.

**Comment by josephdadams** [comment]
fixed in latest
