### ISSUE TITLE
possible issue with vista shorthand notation

### ISSUE THREAD

**Issue by josephdadams** [josephdadams/presentationbridge-client#31]
vista shorthand notation not being recognized or processed properly per a zoom call with a user

**Comment by jrviz** [comment]
Joseph, did you get an example of the command string that was not working?

**Comment by josephdadams** [comment]
Unfortunately no. So testing/verification will be needed.

**Comment by jrviz** [comment]
I don't know the vista syntax but had a quick look at the documentation.

The command processing in PBC allows for multiple commands separated by a ;
command followed by a : and then comma separated parameters.
<command>:<comma>,<separated>,<parameters>;
The final ; is optional - previous fix :-) 

The vista command looks like it is only a go command via MSC with cuelist and cue parameters so the command structure for that looks OK. Could it be that someone was expecting other commands?

**Comment by josephdadams** [comment]
I agree that it is likely a syntax issue on the user end. Let's close this and we can re open should someone else experience the issue.
