### ISSUE TITLE
help popup not working

### ISSUE THREAD

**Issue by josephdadams** [josephdadams/presentationbridge-client#4]
@jrviz can you confirm if pressing Help actually shows the help file? On MacOS, I just get a blank modal.

**Comment by jrviz** [comment]
Yes, I get a blank in the packaged version but the help displays ok when run from npm in dev. I see the text is loaded from a file in the html so needs adding to the package. I just did a quick test and got it to work by adding extraFiles to the build section of the json

        "linux": {
            "target": [
                "AppImage",
                "deb"
            ],
            "category": "Network;Chat"
        },
        "extraFiles": ["help.md"]
    }
}

I can put this into a PR when I get some time or you could add it?

From: Joseph Adams ***@***.***>
Sent: 30 July 2021 04:45
To: josephdadams/presentationbridge-client ***@***.***>
Cc: James Rankin ***@***.***>; Mention ***@***.***>
Subject: [josephdadams/presentationbridge-client] help popup not working (#4)


@jrviz<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjrviz&data=04%7C01%7C%7Ce3dd4ca807414ff42fdd08d9530c5d0f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637632134825328456%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=buYSouDddLQvLu0eh5VCVReI0wipLSpd3sM5MJl2tXw%3D&reserved=0> can you confirm if pressing Help actually shows the help file? On MacOS, I just get a blank modal.

-

**Comment by josephdadams** [comment]
Fixed in latest
