### ISSUE TITLE
HTTP Get request not working

### ISSUE THREAD

**Issue by PKCubed** [josephdadams/presentationbridge-client#48]
I'm using pp7 to link to a home assistant server for my floodlights. I setup the link: 

http://10.0.1.3:1880/endpoint/stagefloodwhite

to turn the floodlights white, but it is not triggered when I click on the slide in pro presenter.

Does the link not work with a port? If not, can this be implemented?

This is the line I have in the slide notes

http:get,http://10.0.1.3:1880/endpoint/stagefloodwhite;

(The link does work when I type it into my browser)

**Comment by josephdadams** [comment]
I fixed this in the latest release if you want to go try it out.
