### ISSUE TITLE
ProPresenter will not connect with new version

### ISSUE THREAD

**Issue by brianmwebber** [josephdadams/presentationbridge-client#56]
Just tried to install the new new version (1.1.0) both through the update dialog and uninstalling it and doing a clean install and when I put in the ip address, port information, and display password, it just sits on "connecting" and doesn't connect. I am able to ping the propresenter computer and run the control web page with no issue.

Running Windows 10

I am not sure if this is part of the issue or not but when I try to uninstall, there are always 2 versions in the app list, both the 1.0.15 and the 1.1.0. When I choose to uninstall the latest, the old one still remains and gives me an error that it cannot find the uninstall program. Also, I have had to do a system restore in order to even get the old version to install. When I try to install, it gets stuck with the installing dialog, the bar gets almost halfway and then just sits there.

**Comment by josephdadams** [comment]
This will be fixed in `v1.1.1.`
