### ISSUE TITLE
Build failing to publish latest.yml and executable images

### ISSUE THREAD

**Issue by jrviz** [josephdadams/presentationbridge-client#9]
Actions are running after a new release is defined and a push of the package.json 

Log file show completion of build activities but failure to publish because of a mismatch of type (release and draft)

**Comment by josephdadams** [comment]
@MatteoGheza i noticed that the electron client throws an error if the latest release does not have the “latest.yml” file. We prob need to do a catch for this and just end the auto update function for that interval. I thought we should also do the same for TA which is why I tagged yoy

**Comment by MatteoGheza** [comment]
@jrviz have you tried publishing a new version without creating a new release in Github or without setting the "draft" attribute?
Besides, I think that Electron AutoUpdater doesn't support the "draft" attribute.

**Comment by jrviz** [comment]
Where is the draft attribute set? I have run a rebuild and can see where the publish process fails because of the type mismatch but I can't see where to set the type
